#!/bin/sh

find  "$1" -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' -type f |

while read -r  line ; do
	if [ -z $(grep "$line" "$1/myprimarycolours.txt") ]; then
		echo "Analysing : $(echo $line | sed 's/.*\///g')" &&
		convert "$line" +dither -colors 5 temp.png &&
		identify  -verbose temp.png | 
		grep ' [0-9]: ' | 
		awk '{print substr($3, 1,7)}'| 
		tr -d '\n' |
		rev | cut -b 8- | rev |
		xargs -I{} echo "'$line\'{}" >> $1/myprimarycolours.txt
	fi
done 

rm temp.png
